project_name             = "broker"
environment              = "prod"
bedrock_model_id         = "amazon.nova-2-lite-v1:0"
lambda_timeout           = 60
api_throttle_burst_limit = 20
api_throttle_rate_limit  = 10
use_custom_domain        = false
root_domain              = ""  # Replace with your actual domain
ld_library_path          = "/opt/poppler/lib:/var/lang/lib:/lib64:/usr/lib64"
poppler_path             = "/opt/poppler/bin"