project_name             = "broker"
environment              = "dev"
bedrock_model_id         = "amazon.nova-2-lite-v1:0"
lambda_timeout           = 60
api_throttle_burst_limit = 10
api_throttle_rate_limit  = 5
use_custom_domain        = false
root_domain              = ""
ld_library_path          = "/opt/lib:/var/lang/lib:/lib64:/usr/lib64" # Need to be carefull here as it can be contain folder poppler - /opt/poppler/lib:/var/lang/lib:/lib64:/usr/lib64
poppler_path             = "/opt/bin" # Need to be carefull here as it can be contain folder poppler - /opt/poppler/bin